version: "3.8"
services:
  ynab:
    build: .
    image: ynab-cli
    volumes:
      - .:/home/app_user
    stdin_open: true
    tty: true
    command: /bin/bash


  test:
    build: .
    volumes:
      - .:/home/app_user
    # stdin_open: true
    # tty: true
    command: ./run_tests.sh

