version: "3.8"
services:
  ynab:
    build: .
    image: ynab-cli
    volumes:
      - ./data:/home/app_user/data
    stdin_open: true
    tty: true
    command: python app/cli.py


  test:
    build: .
    volumes:
      - .:/home/app_user
    # stdin_open: true
    # tty: true
    command: ./run_tests.sh

